name: quickmd-nf
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - git
  - python>=3.8
  - docopt
  - procps-ng
  - openmm
  - pdbfixer
  - numpy
  - matplotlib
  - pandas
  - mdanalysis